version: '3'
services:

  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    restart: always

  app:
    build: .
    # image: rails
    container_name: 'app'
    command: bundle exec rackup -o 0.0.0.0 -p 80 config.ru
    ports:
      - "80:80"
    # environment:
    #   VIRTUAL_PORT: 80
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    restart: always

  schemaspy:
    image: schemaspy/schemaspy:latest
    volumes:
      - ./schemaspy/output:/app/html:rw
      - ./schemaspy/schemaspy.properties:/app/schemaspy.properties:ro
    environment:
      - LANG=ja_JP.UTF-8
      - TZ=Asia/Tokyo
    working_dir: "/app"
    command: "java -jar schemaspy.jar"
    depends_on:
      - db
