# SinatraにBundler導入〜起動まで
# https://qiita.com/nochifuchi/items/be5d8d425f8a6c5b92df

# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "rake"
#gem "puma"

gem "sinatra"
gem "sinatra-contrib"
gem "sinatra-reloader"
gem "tux"# use sinatra on terminal...?

gem "activerecord"
gem "sinatra-activerecord"
gem "pg"
