require 'sinatra/activerecord'
require 'sinatra/activerecord/rake'
#require './app'
require "./db/db.rb"

# namespace :db do
#     task :load_config do
#         require "./db/db.rb"
#     end
# end